### ISSUE TITLE
Pass authentication information along to Event#object

### ISSUE THREAD

**Issue by joelmccracken** [Clever/clever-ruby#77]
There is an issue in the clever gem where authentication information is not provided to clever objects returned from events. IE, if you do:

```
x = event.object
```

Any subsequent action with `x` that hits the clever API will fail.

@TheJefe fixed the same problem somewhere else a while ago:

https://github.com/Clever/clever-ruby/commit/e7b012b44d0e1ce52d8eab6507a94e017b46f6b3

This issue ends up manifesting itself in our code base in really weird ways.
In order to work around it, we have the clever object from an Event, and then we re-fetch it since the first one doesn't have the correct authentication.

**Comment by aashay** [comment]
Hey Joel,

Can you clarify this a bit more for me? I'm probably not understanding the request.  I ran the following script (via irb) and I can't reproduce the auth issue.  I grab an event, grab the "object" on that event, and then I follow a Clever ID from that object to another object (presumably hitting the API).

Apologies if I'm missing something here, I'm not as familiar with our ruby gem as some other folks here.

Take a look below:

```
irb(main):025:0> require 'clever-ruby'
=> false
irb(main):026:0>
irb(main):027:0*   Clever.configure do |config|
irb(main):028:1*       config.token = 'DEMO_TOKEN'
irb(main):029:1>   end
=> "DEMO_TOKEN"
irb(main):030:0> firstEvent = Clever::Event.first
=> #<Clever::Event:0x3fc2b954c214> JSON: {
  "id": "56ba4e56e2f8dff2c0e90249",
  "data": {
    "object": {
      "teachers": [
        "530e5955d50c310f36112c15"
      ],
      "period": "5",
      "teacher": "530e5955d50c310f36112c15",
      "name": "Grade 3 Math, Class 301 - 301 - S. Block",
      "district": "4fd43cc56d11340000000005",
      "students": [
        "530e5962049e75a9262d015a",
        "530e5963049e75a9262d0219",
        "530e5964049e75a9262d0270",
        "530e5964049e75a9262d02cf",
        "530e5964049e75a9262d02fc",
        "530e5965049e75a9262d0341",
        "530e5965049e75a9262d0343",
        "530e5965049e75a9262d038d",
        "530e5965049e75a9262d03a7",
        "530e5966049e75a9262d0415",
        "530e5966049e75a9262d0439",
        "530e5966049e75a9262d0458",
        "530e5966049e75a9262d04d5",
        "530e5967049e75a9262d04f4",
        "530e5967049e75a9262d051f"
      ],
      "last_modified": "2016-02-09T20:38:38.575Z",
      "sis_id": "771",
      "term": {
        "start_date": "2012-08-01",
        "end_date": "2013-06-01",
        "name": "Y1"
      },
      "school": "530e595026403103360ff9fe",
      "course_name": "Grade 3 Math, Class 301",
      "course_number": "301",
      "subject": "math",
      "created": "2014-02-26T21:15:38.738Z",
      "grade": "3",
      "id": "530e597a049e75a9262d0baf"
    },
    "previous_attributes": {
      "students": [
        "530e5960049e75a9262cff56",
        "530e5962049e75a9262d015a",
        "530e5963049e75a9262d0219",
        "530e5964049e75a9262d0270",
        "530e5964049e75a9262d02cf",
        "530e5964049e75a9262d02fc",
        "530e5965049e75a9262d0341",
        "530e5965049e75a9262d0343",
        "530e5965049e75a9262d038d",
        "530e5965049e75a9262d03a7",
        "530e5966049e75a9262d0415",
        "530e5966049e75a9262d0439",
        "530e5966049e75a9262d0458",
        "530e5966049e75a9262d04d5",
        "530e5967049e75a9262d04f4",
        "530e5967049e75a9262d051f"
      ]
    }
  },
  "created": "2016-02-09T20:38:45.804Z",
  "type": "sections.updated"
}
irb(main):031:0> puts firstEvent.type #Happens to return a sections.updated event
sections.updated
=> nil
irb(main):032:0> eventObject = firstEvent.object #A section object
=> #<Clever::Section:0x3fc2b9560048> JSON: {
  "id": "530e597a049e75a9262d0baf",
  "teachers": [
    "530e5955d50c310f36112c15"
  ],
  "period": "5",
  "teacher": "530e5955d50c310f36112c15",
  "name": "Grade 3 Math, Class 301 - 301 - S. Block",
  "district": "4fd43cc56d11340000000005",
  "students": [
    "530e5962049e75a9262d015a",
    "530e5963049e75a9262d0219",
    "530e5964049e75a9262d0270",
    "530e5964049e75a9262d02cf",
    "530e5964049e75a9262d02fc",
    "530e5965049e75a9262d0341",
    "530e5965049e75a9262d0343",
    "530e5965049e75a9262d038d",
    "530e5965049e75a9262d03a7",
    "530e5966049e75a9262d0415",
    "530e5966049e75a9262d0439",
    "530e5966049e75a9262d0458",
    "530e5966049e75a9262d04d5",
    "530e5967049e75a9262d04f4",
    "530e5967049e75a9262d051f"
  ],
  "last_modified": "2016-02-09T20:38:38.575Z",
  "sis_id": "771",
  "term": {
    "start_date": "2012-08-01",
    "end_date": "2013-06-01",
    "name": "Y1"
  },
  "school": "530e595026403103360ff9fe",
  "course_name": "Grade 3 Math, Class 301",
  "course_number": "301",
  "subject": "math",
  "created": "2014-02-26T21:15:38.738Z",
  "grade": "3"
}
irb(main):033:0> puts eventObject.teacher.name #returns {:first=>"Santa", :middle=>"M", :last=>"Block"}
{:first=>"Santa", :middle=>"M", :last=>"Block"}
=> nil
irb(main):034:0>
```

**Comment by joelmccracken** [comment]
Over the weekend, I tried to reproduce this, but couldn't. I'm not sure that this is still an issue -- I'll close it for now, and re-open it in the future if we find that it certainly is a problem.

**Comment by joelmccracken** [comment]
I just reproduced this:

```
2.2.4 :019 > clever_district = Clever::District.retrieve('4fd43cc56d11340000000005', 'DEMO_TOKEN')
 => #<Clever::District:0x5bee628> JSON: {"id":"4fd43cc56d11340000000005","auth_token":"DEMO_TOKEN","name":"Demo District"}
2.2.4 :020 > clever_district.event_pages.first.first.object.sections
Clever::AuthenticationError: No API key provided. (HINT: set your API key using "Clever.configure { |config| config.api_key = <API-KEY> }" or your token using "Clever.configure { |config| config.token =
 <TOKEN> }" or pass the district token as a second argument to retrieve)
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/clever-ruby-0.13.1/lib/clever-ruby.rb:194:in `check_authorization'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/clever-ruby-0.13.1/lib/clever-ruby.rb:210:in `request'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/clever-ruby-0.13.1/lib/clever-ruby/api_resource.rb:115:in `refresh'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/clever-ruby-0.13.1/lib/clever-ruby/api_resource.rb:146:in `get_link_uri'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/clever-ruby-0.13.1/lib/clever-ruby/api_resource.rb:168:in `block (2 levels) in initialize'
        from (irb):20
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/railties-4.2.5.2/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/railties-4.2.5.2/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.2.4@apangea/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

It looks like the issue is when events are retrieved through event pages, specifically.
