### ISSUE TITLE
School data parsing issue

### ISSUE THREAD

**Issue by ReviakinAleksey** [Clever/clever-ruby#97]
#98  data parsing failed when "" passed high_grade value.
This event was received from Clever Events API:
```json
{
      "data": {
        "type": "schools.updated",
        "data": {
          "object": {
            "last_modified": "2017-08-09T02:12:56.190Z",
            "nces_id": "470455001816",
            "district": "57a0b1d6def84101000000d8",
            "phone": "(615) 555-5555",
            "mdr_number": "1234568",
            "high_grade": "",
            "created": "2016-08-11T11:46:56.767Z",
            "name": "Carroll-Oakland Elementary",
            "school_number": "005",
            "low_grade": "",
            "sis_id": "005",
            "location": {
              "address": "4664 Huners Point PK",
              "city": "Lebanon",
              "state": "TN",
              "zip": "37087"
            },
            "id": "57ac65b02eaddb2064000016"
          },
          "previous_attributes": {
            "low_grade": "",
            "high_grade": ""
          }
        },
        "created": "2017-08-09T02:16:28.224Z",
        "id": "598a70777c09dc346c8e4939"
      },
      "uri": "/v1.2/events/598a70777c09dc346c8e4939"
    }
```
As you may notice low_grade and high_grade fields are set to "", after parsing such event to clever-ruby it causing following exception:
```ruby
expected no Exception, got #<ArgumentError: invalid value for 'high_grade', must be one of ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "PreKindergarten", "Kindergarten", "PostGraduate", "Other"].> with backtrace:
  # ./lib/clever-ruby/models/school.rb:204:in `high_grade='
  # ./lib/clever-ruby/models/school.rb:266:in `block in build_from_hash'
  # ./lib/clever-ruby/models/school.rb:258:in `each_pair'
```

**Comment by ReviakinAleksey** [comment]
Ups, looks like this lib was auto generated by swagger, hence fix should be implemented in swagger definitions repo. Or may be this is an server side issue?

**Comment by meliaj** [comment]
Hi Aleksey! Are you still seeing this issue today? We were sending these values unintentionally but the problem should be fixed now.

**Comment by ReviakinAleksey** [comment]
Hello, yes i still see empty fields inside this event
